# Generated by Django 2.2.7 on 2019-11-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni_checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lab',
            new_name='Row',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='lab_name',
            new_name='row_name',
        ),
    ]
