# Generated by Django 2.2.7 on 2019-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_checker', '0003_auto_20191117_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='row',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
