# Generated by Django 2.2.7 on 2019-11-20 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uni_checker.models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_checker', '0007_auto_20191118_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_name']},
        ),
        migrations.AddField(
            model_name='item',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='number_of_read_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100, unique=True, validators=[uni_checker.models.validate_test]),
        ),
        migrations.AlterField(
            model_name='row',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 16, 29, 18, 102608, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='row',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_checker.Item', validators=[uni_checker.models.validate_test]),
        ),
    ]
