# Generated by Django 2.2.7 on 2019-11-20 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uni_checker.models


class Migration(migrations.Migration):

    dependencies = [
        ('uni_checker', '0008_auto_20191120_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2019, 11, 20, 18, 58, 24, 496335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='row',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_checker.Item'),
        ),
        migrations.AlterField(
            model_name='row',
            name='row_name',
            field=models.CharField(max_length=100, validators=[uni_checker.models.validate_test]),
        ),
    ]
