# Generated by Django 2.2.7 on 2019-11-23 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uni_checker', '0009_auto_20191120_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2019, 11, 23, 9, 30, 47, 47538, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='row',
            name='row_name',
            field=models.CharField(max_length=100),
        ),
    ]
