# Generated by Django 2.2.7 on 2019-11-29 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uni_checker', '0011_auto_20191129_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='has_deadline',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='number_of_read_questions',
            field=models.IntegerField(default=0, verbose_name='read questions'),
        ),
        migrations.AlterField(
            model_name='row',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2019, 11, 29, 21, 13, 39, 560396, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='row',
            name='row_name',
            field=models.CharField(default='Lab', max_length=10),
        ),
        migrations.CreateModel(
            name='ItemUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(blank=True, max_length=10)),
                ('material_link', models.URLField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_checker.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uni_checker.Item')),
            ],
        ),
    ]
